### ISSUE TITLE
Link to wrong image file(archetypes)

### ISSUE THREAD

**Issue by ssetoredhat** [rh-mad-workshop/mad-dev-guides-m1#7]
Please check, as it may be wrong.

https://github.com/rh-mad-workshop/mad-dev-guides-m1/blob/ocp-4.15/documentation/modules/ROOT/pages/2-assessment.adoc?plain=1#L93
-> mta-archetypes.png ?

https://github.com/rh-mad-workshop/mad-dev-guides-m1/blob/ocp-4.15/documentation/modules/ROOT/pages/2-assessment.adoc?plain=1#L97
-> mta-archetypes-summer.png ?

**Comment by danieloh30** [comment]
Yeah both images are correct!
